// <auto-generated />
namespace AppForVaccine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Cityrequiredtrue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cityrequiredtrue));
        
        string IMigrationMetadata.Id
        {
            get { return "202303281010538_City @required = true"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
